### ISSUE TITLE
Posibles errores al leer el fichero

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/ExamenMayo2018#1]
https://github.com/Javierfs94/ExamenMayo2018/blob/5742436248eec0eaad0eece109134626d8e93578/src/exMayo2018/gui/Principal.java#L52
Quizás el mensaje debería ser ERROR_MESSAGE
El mensaje debes particulizarlo (IOException.getMensaje())
¿No hay más excepciones?

**Comment by Javierfs94** [comment]
Arreglado
