### ISSUE TITLE
Refactoriza

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/ExamenMayo2018#3]
https://github.com/Javierfs94/ExamenMayo2018/blob/5742436248eec0eaad0eece109134626d8e93578/src/exMayo2018/funcionalidad/Fichero.java#L38

No es salida, sino entrada (Read)
Haces demasiadas cosas aparte de leer. La comprobación de si fichero existe debe estar fuera. Si el fichero no existe, entonces NO LEES.
Extrae método fichero existe (para leer y escribir)

**Comment by Javierfs94** [comment]
Arreglado
